### ISSUE TITLE
Next: update examples for Riot3

### ISSUE THREAD

**Issue by cognitom** [riot/examples#39]
Your contributions are always welcome!
Feel free to send PRs to `next` branch. Thank you :wink:

- [x] bug-reporter - checked by @cognitom
- [x] color-palette - fixed by @cognitom 8cf398173189e7bfb774d10f1d55588905998c31
- [x] es6 - checked by @cognitom
- [x] if-else-elseif - #40 fixed by @cognitom, @GianlucaGuarini   ~~567683d962162ff7a694dd3b9676a32b1517762a~~ c9570fb83c6b9d041f84d681f9c3d6a9e1b81725
- [x] todo-app-precompiled - #41 #42 #44 fixed by @k-kuwahara
- [x] todo-app - #43 #44 fixed by @k-kuwahara
- [x] live-ajax-search @gianlucaguarini
- [x] animated-list-reordering @gianlucaguarini
- [x] timer
- [x] observables
- [x] mixins - checked by @k-kuwahara 
- [x] live-editor
- [x] live-filtering
- [x] plunker
- [x] pre-process-less
- [x] router-complex
- [x] router-history-api
- [x] router-page-switcher
- [x] rollup
- [ ] webpack

**Comment by cognitom** [comment]
Contributing instruction:
1. fork from `next` branch of `riot/examples`
2. check an example not checked yet above
3. if OK, comment at this issue
4. if NG, [create new issue](https://github.com/riot/examples/issues/new) about it
5. if you know how to fix, send your PR to `next` branch!

Thank you!

**Comment by kkeeth** [comment]
@cognitom 

I have checked `examples/mixins` and I think it is no problem!!
But, the version of riotjs being read by the following application remained old.

`http://riotjs.com/examples/plunker/?app=mixins`

**Comment by cognitom** [comment]
@k-kuwahara cool! I've update the check list above.

As you mention, plunker links refer to `master` actually. I'll merge `next` into `master` after the release of Riot 3, so don't worry. Thank you!
http://riotjs.com/examples/plunker/?app=mixins

**Comment by GianlucaGuarini** [comment]
@cognitom I have reordered your list, examples done go on the top ;)

**Comment by kkeeth** [comment]
@cognitom 
I have checked the following applications.
- observables
- timer
- webpack

But, there is one problem about `webpack`, I will create new issue.

**Comment by cognitom** [comment]
Almost done!
Rollup and webpack might need update the package itself.
Basically, I think we can merge this after the release of Riot 3.0.0.

**Comment by GianlucaGuarini** [comment]
great work guys!

**Comment by GianlucaGuarini** [comment]
I have added a note on our play page http://riotjs.com/play/
We will remove it once we will be done here ;)

**Comment by cognitom** [comment]
OK, landed. #47
Thank you so much guys!!

**Comment by cognitom** [comment]
I've removed the note, too.
http://riotjs.com/play/

**Comment by GianlucaGuarini** [comment]
@cognitom awesome thank you
